### ISSUE TITLE
URL is too long when sharing link

### ISSUE THREAD

**Issue by seangrant82** [neo4j-labs/arrows.app#13]
Currently when you share the link, the URL is enormous. It would beneficial to have a URL shortener built-in

**Comment by apcj** [comment]
Hi @seangrant82 I agree they are enormous! However, I'm going to consider this a known limitation. I don't want to use an external URL shortening service, because this would entail sending all your data (in encoded form) to a third party. I suspect they also have a maximum URL length :-)

I think the right solution here to to expand the range of storage options, as you suggest in #14 .
