### ISSUE TITLE
Feature request - bigger arcs on multi relationship connections

### ISSUE THREAD

**Issue by graphadvantage** [neo4j-labs/arrows.app#20]
Wow!

What a terrific upgrade the arrows.app is!  Nice work, so much more useful and handy for designing graphs and communicating graph designs with clients.

One tiny, tiny ask - would it be possible to increase the arc (or make the arc slider configurable) for multi-relationships?

Currently the arc is sufficiently shallow that the relationship type labels overlap and are difficult to read.

Thanks,

Michael

**Comment by apcj** [comment]
Hi @graphadvantage thanks for the feedback!

I will certainly adjust the defaults here because they are clearly sub-optimal. In the long term, I'll also make "deflection" configurable as you suggest.

For right now, the best you can do is to adjust `type-font-size` or `detail-position` in the inspector. If you do this with nothing selected, it will apply for all relationships.

**Comment by apcj** [comment]
Hi @graphadvantage , finally remembered to follow up here. A couple of weeks ago we changed the default chunky style, reducing `type-font-size`. Here is how a pair of relationships look now:
![image](https://user-images.githubusercontent.com/98962/124384359-b731db80-dcc8-11eb-98cf-27e13f86d2fd.png)

Hopefully this is much better for your use case. Also, I forgot to mention it in the previous comment, but I think we have always supported `margin-peer` which I think does what you are asking for in the original request. Here is the same graph, but with `margin-peer` set to 40 instead of the default 20:
![image](https://user-images.githubusercontent.com/98962/124384341-99fd0d00-dcc8-11eb-87a7-f9f4833369e6.png)

**Comment by graphadvantage** [comment]
Thanks Alastair!

It works great - I was doing some modeling this week and I saw the updates.  Thank you!

Michael
