### ISSUE TITLE
Feature request-Integrate arrows to other websites

### ISSUE THREAD

**Issue by armensanoyan** [neo4j-labs/arrows.app#27]
I am curios if there is a way to integrate the arrows.app into my website. I have tried arrows.app 2 for creating graphs by just painting them and it works perfect. It would be great if I could let my users to create graphs inside my website so my question is, does arrows.app provide api or any tool to have this interface in my website

**Comment by apcj** [comment]
Hi @armensanoyan we are not providing any library or API at this stage, but I can definitely see how that would be useful. Probably we will create a separate library that you could integrate into your website. Closing this issue for now, because I don't think this is a core aim of arrows.app in its current incarnation.
