### ISSUE TITLE
Color-code nodes and relationships, based on types

### ISSUE THREAD

**Issue by versusnja** [neo4j-labs/arrows.app#29]
It would be great to automatically assign colors (or even better - styles) to nodes and relationships based on their types.

So, all notes "Actor" are pink and "Movie" are blue etc.

Or, maybe even easier - just save styles so that you can reuse them on other nodes/relationships.

**Comment by apcj** [comment]
Hi @versusnja this is the kind of thing that you can do in [Neo4j Bloom](https://neo4j.com/product/bloom/) or [Neo4j Browser](https://neo4j.com/docs/browser-manual/current/). We could certainly add this to Arrows, but I'm reluctant to do so, just to keep things simple, and focus on manual styling. At some point there should be better integration with Bloom and Browser, so that you can take advantage of the rules-base styling that those tools provide.

**Comment by versusnja** [comment]
@apcj thanks for your comments. Before you close this completely, here are some arguments:

- bloom and browser require data to be already in place, while arrows.app is used in data prototyping, where there is no data
- "save style" feature can be simplified to simply pre-defined styles or colors. This will already provide a great added value, but will require a few lines of JS. Some sort of color-palette would suffice

I hope this will help you decide.
