### ISSUE TITLE
docker version?

### ISSUE THREAD

**Issue by donnels** [neo4j-labs/arrows.app#34]
Dear neo4j team,
Thanks for the arrows.app. I find it very useful. And it's exactly what I need for drafting graphs quickly.

My issue is that it's only online so while It's good I'm ending up using only the original and more simple arrows open source version as I can run it locally in a container or locally and keep the data I put into it confidential.

Q: Is there a plan to make a version of this that is either open source or standalone so that one can put sensitive information into it?

**Comment by apcj** [comment]
Hi @donnels great that you find arrows useful. Thanks for asking about using it for confidential data. I'm afraid that making a docker version wouldn't really help, because arrows.app is already implemented as a 'serverless' app. Behind the scenes it's only static HTML and Javascript, just like classic arrows. Also, just like classic arrows, by default arrows.app stores your data in your local web browser storage, so it never goes to a server. However, you can not guarantee that we won't change the arrows.app code to send your data to a server. I don't think having a Docker image for arrows would help here - because isolating the server part isn't enough - your web browser can still send data wherever it likes.

If you want to host arrows.app yourself, like you did with classic arrows, this is still possible. Just use "File / Save As" from your web browser and you will get all of the static files you need for it to work. Then open the HTML file, or set up a simple web server to serve the files. You could even make your own docker image from these files. Saving to Google Drive will not work, but everything should work fine.
