### ISSUE TITLE
How to clean the board

### ISSUE THREAD

**Issue by cat971216** [neo4j-labs/arrows.app#52]
Hello, 

I am using arrow tool, and I find that the browser always keep the diagram I drew last time, which I need to clean maually one node by another. Even if I clean the browser cache, it still keeps. And I cannot replace it with new diagram by changing the export markup code. How can I open a new arrow tool board every time I use it?

**Comment by apcj** [comment]
Hi @cat971216 I think you can achieve what you want by using the menu in the top-left corner:

![image](https://user-images.githubusercontent.com/98962/151673029-ee2246e8-359a-47aa-ae85-66475a9a071f.png)

I will update the video sometime to show this in action, because a few others have also not found this :-)
