### ISSUE TITLE
Feature Request - Grid Paper Background

### ISSUE THREAD

**Issue by johnstonmatt** [neo4j-labs/arrows.app#64]
When building a complex graph in the web application it can become difficult to know true horizontal and vertical because things can snap to the page with red highlights for other reasons. 

A grid background in one of the themes would help for laying things out by providing a frame of reference.

I did try importing a grid image, but it ended up only covering a small region of my graph instead of tiling the entire plane like I expected.

Huge improvement since I first started using version 1 of arrows by the way, thanks for the great work!

**Comment by apcj** [comment]
Hi @johnstonmatt thanks for the feedback. We could certainly add a grid, but first I'm interested what is happening with stray guides that obscure true horizontal or vertical. Does that happen often? My aim is that the guides are smart enough to just 'do the right thing' which sounds like isn't happening here. Any chance you could capture a screen shot so that I can understand what is happening?

**Comment by johnstonmatt** [comment]
I've struggled to replicate the issue, but I'll come back if I see it again.

I _think_ what I was seeing is that there were enough other nodes and relationships on the page that I was seeing guides for alignment with other nodes that I was not trying to align with.

I would guess everything is working as intended.
