### ISSUE TITLE
Shortcuts not working

### ISSUE THREAD

**Issue by SreedevSB** [neo4j-labs/arrows.app#9]
Shortcuts except Delete and Edit are not working.

**Comment by wadael** [comment]
Noticed this on Linux+FFOX 83 too
ctrl+D is still assigned to bookmarking even though I have a node selected

same on chromium Version 87.0.4280.88

**Comment by apcj** [comment]
Hi @SreedevSB - thanks for reporting this. Can you tell me what OS and Browser you are using?

**Comment by apcj** [comment]
@wadael thanks for reporting too. It sounds like this should be relatively easy to fix. Do you find the same thing at @SreedevSB ? For example, does Ctrl+A work for you?

**Comment by SreedevSB** [comment]
Hi @apcj, I am using Chrome 87.0.4280.141 (64-bit) on Windows 10 Pro v.1909.

**Comment by apcj** [comment]
Hi @wadael @SreedevSB - thanks for the info. This should now be fixed. Please make sure you hard-refresh the page or clear your cache to ensure you have the latest code.

**Comment by wadael** [comment]
I validate the fix is working for Ctrl+D as it does duplicate the selected node

**However,** CtrlZ is not working (FFox , Chromium) BUT I suspect it is related to my install and must be because of shortcut handling by higher program than the browser.

I remember someday I was asked to choose between app and system as first recipient for the shortcuts.
Was it in Mate/compiz/cinnamon/marco/??? (dont know) 
Was it with this distro ? (maybe) 
Was it intellij ? netbeans ?

I cant find this interesting setting.

Thanks again for this great application.
